/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationIndexRouteImport } from './routes/conversation/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ConversationConversationIdRouteImport } from './routes/conversation/$conversationId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIndexRoute = ConversationIndexRouteImport.update({
  id: '/conversation/',
  path: '/conversation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationConversationIdRoute =
  ConversationConversationIdRouteImport.update({
    id: '/conversation/$conversationId',
    path: '/conversation/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
  '/auth/': typeof AuthIndexRoute
  '/conversation/': typeof ConversationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
  '/auth': typeof AuthIndexRoute
  '/conversation': typeof ConversationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
  '/auth/': typeof AuthIndexRoute
  '/conversation/': typeof ConversationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/conversation/$conversationId'
    | '/auth/'
    | '/conversation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/conversation/$conversationId'
    | '/auth'
    | '/conversation'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/conversation/$conversationId'
    | '/auth/'
    | '/conversation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConversationConversationIdRoute: typeof ConversationConversationIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ConversationIndexRoute: typeof ConversationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/': {
      id: '/conversation/'
      path: '/conversation'
      fullPath: '/conversation/'
      preLoaderRoute: typeof ConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$conversationId': {
      id: '/conversation/$conversationId'
      path: '/conversation/$conversationId'
      fullPath: '/conversation/$conversationId'
      preLoaderRoute: typeof ConversationConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConversationConversationIdRoute: ConversationConversationIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  ConversationIndexRoute: ConversationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
